{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOPF8hrwhxYpw5OZKNU+5c+"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 32,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "VoOS5nfPKJqd",
        "outputId": "564c5211-6ffa-42f6-ae75-2ac280c8a059"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dataset loaded succesfully\n",
            "duplicates removen successfully\n",
            "handled perfectly\n",
            "Encoding Successful\n",
            "Date Columns Processed\n",
            "Date Features Created\n",
            "\n",
            "Dataset Shape\n",
            "(500, 32)\n",
            "\n",
            "Data Types\n",
            "EmployeeID          datetime64[ns]\n",
            "Name                datetime64[ns]\n",
            "Age                 datetime64[ns]\n",
            "Gender              datetime64[ns]\n",
            "Department          datetime64[ns]\n",
            "Salary              datetime64[ns]\n",
            "City                datetime64[ns]\n",
            "JoinDate            datetime64[ns]\n",
            "EmployeeID_Year              int32\n",
            "EmployeeID_Month             int32\n",
            "EmployeeID_Day               int32\n",
            "Name_Year                    int32\n",
            "Name_Month                   int32\n",
            "Name_Day                     int32\n",
            "Age_Year                     int32\n",
            "Age_Month                    int32\n",
            "Age_Day                      int32\n",
            "Gender_Year                  int32\n",
            "Gender_Month                 int32\n",
            "Gender_Day                   int32\n",
            "Department_Year              int32\n",
            "Department_Month             int32\n",
            "Department_Day               int32\n",
            "Salary_Year                  int32\n",
            "Salary_Month                 int32\n",
            "Salary_Day                   int32\n",
            "City_Year                    int32\n",
            "City_Month                   int32\n",
            "City_Day                     int32\n",
            "JoinDate_Year                int32\n",
            "JoinDate_Month               int32\n",
            "JoinDate_Day                 int32\n",
            "dtype: object\n",
            "\n",
            "Missing Values\n",
            "EmployeeID          0\n",
            "Name                0\n",
            "Age                 0\n",
            "Gender              0\n",
            "Department          0\n",
            "Salary              0\n",
            "City                0\n",
            "JoinDate            0\n",
            "EmployeeID_Year     0\n",
            "EmployeeID_Month    0\n",
            "EmployeeID_Day      0\n",
            "Name_Year           0\n",
            "Name_Month          0\n",
            "Name_Day            0\n",
            "Age_Year            0\n",
            "Age_Month           0\n",
            "Age_Day             0\n",
            "Gender_Year         0\n",
            "Gender_Month        0\n",
            "Gender_Day          0\n",
            "Department_Year     0\n",
            "Department_Month    0\n",
            "Department_Day      0\n",
            "Salary_Year         0\n",
            "Salary_Month        0\n",
            "Salary_Day          0\n",
            "City_Year           0\n",
            "City_Month          0\n",
            "City_Day            0\n",
            "JoinDate_Year       0\n",
            "JoinDate_Month      0\n",
            "JoinDate_Day        0\n",
            "dtype: int64\n",
            "Dataset Saved\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/tmp/ipykernel_504/3402591777.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
            "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
            "\n",
            "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
            "\n",
            "\n",
            "  self.df[column].fillna(median,inplace = True)\n",
            "/tmp/ipykernel_504/3402591777.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
            "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
            "\n",
            "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
            "\n",
            "\n",
            "  self.df[column].fillna(mode,inplace = True)\n"
          ]
        }
      ],
      "source": [
        "import numpy as np\n",
        "import pandas as pd\n",
        "import time\n",
        "from sklearn.preprocessing import LabelEncoder\n",
        "\n",
        "class DataCleaner:\n",
        "  def __init__(self,file_path):\n",
        "   self.file_path = file_path\n",
        "   self.df = None\n",
        "\n",
        "  def load_data(self):\n",
        "    self.df =pd.read_csv(self.file_path)\n",
        "    print(\"Dataset loaded succesfully\")\n",
        "\n",
        "  def remove_duplicates(self):\n",
        "    before = len(self.df)\n",
        "    self.df.drop_duplicates(inplace = True)\n",
        "    after = len(self.df)\n",
        "    print(\"duplicates removen successfully\")\n",
        "\n",
        "  def handle_missing_values(self):\n",
        "    for column in self.df.columns:\n",
        "      if self.df[column].dtype == \"object\":\n",
        "        mode = self.df[column].mode()[0]\n",
        "        self.df[column].fillna(mode,inplace = True)\n",
        "      else:\n",
        "        median = self.df[column].median()\n",
        "        self.df[column].fillna(median,inplace = True)\n",
        "\n",
        "    print(\"handled perfectly\")\n",
        "\n",
        "  def encoding(self):\n",
        "\n",
        "      encoder = LabelEncoder()\n",
        "\n",
        "      for column in self.df.select_dtypes(include=[\"object\"]).columns:\n",
        "\n",
        "          self.df[column] = encoder.fit_transform(self.df[column])\n",
        "\n",
        "      print(\"Encoding Successful\")\n",
        "\n",
        "  def convert_dates(self):\n",
        "\n",
        "          for column in self.df.columns:\n",
        "\n",
        "              try:\n",
        "\n",
        "                  self.df[column] = pd.to_datetime(self.df[column])\n",
        "\n",
        "              except:\n",
        "\n",
        "                  pass\n",
        "\n",
        "          print(\"Date Columns Processed\")\n",
        "\n",
        "  def create_features(self):\n",
        "\n",
        "          date_columns = self.df.select_dtypes(include=[\"datetime64[ns]\"]).columns\n",
        "\n",
        "          for column in date_columns:\n",
        "\n",
        "              self.df[column+\"_Year\"] = self.df[column].dt.year\n",
        "              self.df[column+\"_Month\"] = self.df[column].dt.month\n",
        "              self.df[column+\"_Day\"] = self.df[column].dt.day\n",
        "\n",
        "          print(\"Date Features Created\")\n",
        "\n",
        "\n",
        "\n",
        "  def display_sataset(self):\n",
        "      print(\"\\nDataset Shape\")\n",
        "      print(self.df.shape)\n",
        "      print(\"\\nData Types\")\n",
        "      print(self.df.dtypes)\n",
        "      print(\"\\nMissing Values\")\n",
        "      print(self.df.isnull().sum())\n",
        "\n",
        "  def save(self, output_path):\n",
        "      self.df.to_csv(output_path, index=False)\n",
        "      print(\"Dataset Saved\")\n",
        "\n",
        "  def pipeline(self,output_path):\n",
        "      start =time.time()\n",
        "      self.load_data()\n",
        "      self.remove_duplicates()\n",
        "      self.handle_missing_values()\n",
        "      self.encoding()\n",
        "      self.convert_dates()\n",
        "      self.create_features()\n",
        "      self.display_sataset()\n",
        "      self.save(output_path)\n",
        "      end =time.time()\n",
        "\n",
        "  def main():\n",
        "    cleaner = DataCleaner(\"dirty_employee_dataset.csv\")\n",
        "    cleaner.pipeline(\"cleaned_employee_dataset.csv\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "\n",
        "    main()\n"
      ]
    }
  ]
}